linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - depguard

    - errcheck
    - exportloopref
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - bodyclose
    - noctx
    - dogsled
    - gocyclo

  # don't enable:
  # - wsl
  # - gochecknoinits
  # - gomnd

# Options for analysis running.
run:
  skip-files:
    - "internal/pb/*.pb.go$"
    - internal/pb/object.go
