version: "3"

includes:
  client: ./tasks/client.yml
  db: ./tasks/db.yml
  gen: ./tasks/gen.yml
  server: ./tasks/server.yml

vars:
  VERSION:
    sh: git describe --tags --abbrev=0

  DB_HOST: "127.0.0.1"
  DB_PORT: 5432
  DB_USER: "postgres"
  DB_PASS: "password"
  DB_NAME: "dl"
  DB_URI: "postgres://{{.DB_USER}}:{{.DB_PASS}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable"

  GRPC_HOST: "127.0.0.1"
  GRPC_PORT: 5051
  GRPC_SERVER: "{{.GRPC_HOST}}:{{.GRPC_PORT}}"

tasks:
  vars:
    silent: true
    cmds:
      - echo {{toPrettyJson . | shellQuote}}
