version: "3"

includes:
  client: ./tasks/client.yml
  db: ./tasks/db.yml
  gen: ./tasks/gen.yml
  server: ./tasks/server.yml
  tools: ./tasks/tools.yml
  webui: ./tasks/webui.yml

vars:
  VERSION:
    sh: git describe --tags --abbrev=0

  DB_HOST: "localhost"
  DB_PORT: 5432
  DB_USER: "postgres"
  DB_PASS: "password"
  DB_NAME: "dl"
  DB_URI: "postgres://{{.DB_USER}}:{{.DB_PASS}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable"

  GRPC_HOST: "localhost"
  GRPC_PORT: 5051
  GRPC_SERVER: "{{.GRPC_HOST}}:{{.GRPC_PORT}}"

  DEV_TOKEN_ADMIN: '{{.DEV_TOKEN_ADMIN | default "v2.public.eyJzdWIiOiJhZG1pbiIsImlhdCI6IjIwMjEtMTAtMTVUMTE6MjA6MDAuMDM0WiJ9WtEey8KfQQRy21xoHq1C5KQatEevk8RxS47k4bRfMwVCPHumZmVuk6ADcfDHTmSnMtEGfFXdxnYOhRP6Clb_Dw"}}'

tasks:
  test:
    desc: Run tests
    deps:
      - gen:protoc-go
      - task: db:migrate:up
        vars:
          DB_URI: "postgres://{{.DB_USER}}:{{.DB_PASS}}@{{.DB_HOST}}:{{.DB_PORT}}/dl_tests?sslmode=disable"
    cmds:
      - cd test && go test
    env:
      DB_URI: "postgres://{{.DB_USER}}:{{.DB_PASS}}@{{.DB_HOST}}:{{.DB_PORT}}/dl_tests?sslmode=disable"
