version: "3"

vars:
  DEV_TOKEN_ADMIN: '{{.DEV_TOKEN_ADMIN | default "v2.public.eyJzdWIiOiJhZG1pbiIsImlhdCI6IjIwMjEtMTAtMTVUMTE6MjA6MDAuMDM0WiJ9WtEey8KfQQRy21xoHq1C5KQatEevk8RxS47k4bRfMwVCPHumZmVuk6ADcfDHTmSnMtEGfFXdxnYOhRP6Clb_Dw"}}'
  DEV_TOKEN_PROJECT_1: '{{.DEV_TOKEN_PROJECT_1 | default "v2.public.eyJzdWIiOiIxIiwiaWF0IjoiMjAyMS0xMC0xNVQxMToyMDowMC4wMzVaIn2MQ14RfIGpoEycCuvRu9J3CZp6PppUXf5l5w8uKKydN3C31z6f6GgOEPNcnwODqBnX7Pjarpz4i2uzWEqLgQYD"}}'

env:
  DL_TOKEN: "{{.DL_TOKEN | default .DEV_TOKEN_ADMIN}}"
  DL_SKIP_SSL_VERIFICATION: "{{.DL_SKIP_SSL_VERIFICATION | default 1}}"

tasks:
  build:
    desc: Build the dateilager client
    deps:
      - :gen:protoc
    sources:
      - cmd/server/client.go
      - internal/**/*.go
      - pkg/**/*.go
      - go.sum
    generates:
      - bin/client
    cmds:
      - go build {{.BUILD_FLAGS}} -o bin/client cmd/client/main.go
    env:
      CGO_ENABLED: 0
      BUILD_FLAGS: '{{.BUILD_FLAGS | default "-ldflags=-s -w -X github.com/gadget-inc/dateilager/pkg/version.Version={{.VERSION}}"}}'

  get:
    desc: Get
    deps:
      - build
    cmds:
      - bin/client get -project 1 -server "{{.GRPC_SERVER}}" -to {{.TO_VERSION}} -prefix "{{.PREFIX}}"
    vars:
      PREFIX: "{{.PREFIX | default .CLI_ARGS}}"
      TO_VERSION: "{{.TO_VERSION | default -1}}"

  rebuild:
    desc: Rebuild
    deps:
      - build
    cmds:
      - bin/client rebuild -project 1 -server "{{.GRPC_SERVER}}" -to {{.TO_VERSION}} -prefix "{{.PREFIX}}" -dir "{{.DIR}}"
    vars:
      PREFIX: "{{.PREFIX | default .CLI_ARGS}}"
      TO_VERSION: "{{.TO_VERSION | default -1}}"
      DIR: '{{.DIR | default "rebuild"}}'

  simple:
    desc: Update simple inputs
    deps:
      - build
    cmds:
      - scripts/simple_input.sh 1
      - bin/client update -project 1 -server "{{.GRPC_SERVER}}" -dir input/simple
      - scripts/simple_input.sh 2
      - bin/client update -project 1 -server "{{.GRPC_SERVER}}" -dir input/simple
      - scripts/simple_input.sh 3
      - bin/client update -project 1 -server "{{.GRPC_SERVER}}" -dir input/simple

  complex:
    desc: Update complex inputs
    deps:
      - build
    cmds:
      - scripts/complex_input.sh 1
      - bin/client update -project 1 -server "{{.GRPC_SERVER}}" -dir input/complex
      - scripts/complex_input.sh 2
      - bin/client update -project 1 -server "{{.GRPC_SERVER}}" -dir input/complex
      - scripts/complex_input.sh 3
      - bin/client update -project 1 -server "{{.GRPC_SERVER}}" -dir input/complex
