apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: localhost/dateilager:server
    env:
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: server-config
          key: port
    - name: DBURI
      valueFrom:
        configMapKeyRef:
          name: server-config
          key: dburi
    - name: DL_ENV
      valueFrom:
        configMapKeyRef:
          name: server-config
          key: env
    command: ["./server"]
    args: ["-port=$(PORT)", "-dburi=$(DBURI)", "-cert=secrets/tls/tls.crt", "-key=secrets/tls/tls.key", "-paseto=secrets/paseto/paseto.pub"]
    ports:
    - name: api
      containerPort: 5051
      protocol: TCP
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5051", "-tls", "-tls-no-verify", "-service=dateilager.server"]
      initialDelaySeconds: 3
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5051", "-tls", "-tls-no-verify"]
      initialDelaySeconds: 3
    volumeMounts:
    - mountPath: /home/main/secrets/tls
      name: tls-secrets
    - mountPath: /home/main/secrets/paseto
      name: paseto-secrets
  volumes:
  - name: tls-secrets
    secret:
      secretName: server-tls
  - name: paseto-secrets
    secret:
      secretName: server-paseto
