apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: localhost/dateilager:server
    ports:
      - name: api
        containerPort: 5051
        protocol: TCP
    env:
      - name: PORT
        value: ":5051"
      - name: DB_URI
        value: "postgres://postgres@10.1.1.3:5432/dl"
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5051", "-service=dateilager.server"]
      initialDelaySeconds: 3
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5051"]
      initialDelaySeconds: 3
