apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: localhost/dateilager:server
    env:
    - name: PORT
      valueFrom:
        configMapKeyRef:
          name: server-config
          key: port
    - name: DBURI
      valueFrom:
        configMapKeyRef:
          name: server-config
          key: dburi
    - name: DL_ENV
      valueFrom:
        configMapKeyRef:
          name: server-config
          key: env
    command: ["./server"]
    args: ["-port=$(PORT)", "-dburi=$(DBURI)", "-cert=secrets/server.crt", "-key=secrets/server.key", "-paseto=secrets/paseto.pub"]
    ports:
    - name: api
      containerPort: 5051
      protocol: TCP
    # FIXME: Auth & TLS broke the probes
    # readinessProbe:
    #   exec:
    #     command: ["/bin/grpc_health_probe", "-addr=:5051", "-service=dateilager.server"]
    #   initialDelaySeconds: 3
    # livenessProbe:
    #   exec:
    #     command: ["/bin/grpc_health_probe", "-addr=:5051"]
    #   initialDelaySeconds: 3
    volumeMounts:
    - mountPath: /home/main/secrets
      name: secrets
  volumes:
  - name: secrets
    hostPath:
      # FIXME: remove hard coded path
      path: /home/alex/repos/dateilager/dev
      type: Directory
