apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: server
spec:
  containers:
  - name: server
    image: localhost/dateilager:server
    env:
      - name: PORT
        valueFrom:
          configMapKeyRef:
            name: server-config
            key: port
      - name: DBURI
        valueFrom:
          configMapKeyRef:
            name: server-config
            key: dburi
    command: ["./server"]
    args: ["-port=$(PORT)", "-dburi=$(DBURI)"]
    ports:
      - name: api
        containerPort: 5051
        protocol: TCP
    readinessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5051", "-service=dateilager.server"]
      initialDelaySeconds: 3
    livenessProbe:
      exec:
        command: ["/bin/grpc_health_probe", "-addr=:5051"]
      initialDelaySeconds: 3
