// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: internal/pb/cache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PopulateDiskCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopulateDiskCacheRequest) Reset() {
	*x = PopulateDiskCacheRequest{}
	mi := &file_internal_pb_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopulateDiskCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulateDiskCacheRequest) ProtoMessage() {}

func (x *PopulateDiskCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulateDiskCacheRequest.ProtoReflect.Descriptor instead.
func (*PopulateDiskCacheRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{0}
}

func (x *PopulateDiskCacheRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PopulateDiskCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopulateDiskCacheResponse) Reset() {
	*x = PopulateDiskCacheResponse{}
	mi := &file_internal_pb_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopulateDiskCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulateDiskCacheResponse) ProtoMessage() {}

func (x *PopulateDiskCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulateDiskCacheResponse.ProtoReflect.Descriptor instead.
func (*PopulateDiskCacheResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{1}
}

func (x *PopulateDiskCacheResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type SpecializePodRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId      int64                  `protobuf:"varint,1,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	EnvironmentId      int64                  `protobuf:"varint,2,opt,name=environmentId,proto3" json:"environmentId,omitempty"`
	EnvironmentVersion int64                  `protobuf:"varint,3,opt,name=environmentVersion,proto3" json:"environmentVersion,omitempty"`
	PodUuid            string                 `protobuf:"bytes,4,opt,name=podUuid,proto3" json:"podUuid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SpecializePodRequest) Reset() {
	*x = SpecializePodRequest{}
	mi := &file_internal_pb_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecializePodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecializePodRequest) ProtoMessage() {}

func (x *SpecializePodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecializePodRequest.ProtoReflect.Descriptor instead.
func (*SpecializePodRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{2}
}

func (x *SpecializePodRequest) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

func (x *SpecializePodRequest) GetEnvironmentId() int64 {
	if x != nil {
		return x.EnvironmentId
	}
	return 0
}

func (x *SpecializePodRequest) GetEnvironmentVersion() int64 {
	if x != nil {
		return x.EnvironmentVersion
	}
	return 0
}

func (x *SpecializePodRequest) GetPodUuid() string {
	if x != nil {
		return x.PodUuid
	}
	return ""
}

type SpecializePodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecializePodResponse) Reset() {
	*x = SpecializePodResponse{}
	mi := &file_internal_pb_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecializePodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecializePodResponse) ProtoMessage() {}

func (x *SpecializePodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecializePodResponse.ProtoReflect.Descriptor instead.
func (*SpecializePodResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{3}
}

var File_internal_pb_cache_proto protoreflect.FileDescriptor

var file_internal_pb_cache_proto_rawDesc = string([]byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2e, 0x0a,
	0x18, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x35, 0x0a,
	0x19, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0xac, 0x01, 0x0a, 0x14, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c,
	0x69, 0x7a, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x65, 0x6e, 0x76, 0x69,
	0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x12, 0x65, 0x6e, 0x76,
	0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x65, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65,
	0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6f, 0x64,
	0x55, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x55,
	0x75, 0x69, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa0, 0x01, 0x0a,
	0x06, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x50, 0x0a, 0x11, 0x50, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x1c, 0x2e, 0x70,
	0x62, 0x2e, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0d, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x50, 0x6f, 0x64, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x61,
	0x64, 0x67, 0x65, 0x74, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x69, 0x6c, 0x61,
	0x67, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_internal_pb_cache_proto_rawDescOnce sync.Once
	file_internal_pb_cache_proto_rawDescData []byte
)

func file_internal_pb_cache_proto_rawDescGZIP() []byte {
	file_internal_pb_cache_proto_rawDescOnce.Do(func() {
		file_internal_pb_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_cache_proto_rawDesc), len(file_internal_pb_cache_proto_rawDesc)))
	})
	return file_internal_pb_cache_proto_rawDescData
}

var file_internal_pb_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_cache_proto_goTypes = []any{
	(*PopulateDiskCacheRequest)(nil),  // 0: pb.PopulateDiskCacheRequest
	(*PopulateDiskCacheResponse)(nil), // 1: pb.PopulateDiskCacheResponse
	(*SpecializePodRequest)(nil),      // 2: pb.SpecializePodRequest
	(*SpecializePodResponse)(nil),     // 3: pb.SpecializePodResponse
}
var file_internal_pb_cache_proto_depIdxs = []int32{
	0, // 0: pb.Cached.PopulateDiskCache:input_type -> pb.PopulateDiskCacheRequest
	2, // 1: pb.Cached.SpecializePod:input_type -> pb.SpecializePodRequest
	1, // 2: pb.Cached.PopulateDiskCache:output_type -> pb.PopulateDiskCacheResponse
	3, // 3: pb.Cached.SpecializePod:output_type -> pb.SpecializePodResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_cache_proto_init() }
func file_internal_pb_cache_proto_init() {
	if File_internal_pb_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_cache_proto_rawDesc), len(file_internal_pb_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_cache_proto_goTypes,
		DependencyIndexes: file_internal_pb_cache_proto_depIdxs,
		MessageInfos:      file_internal_pb_cache_proto_msgTypes,
	}.Build()
	File_internal_pb_cache_proto = out.File
	file_internal_pb_cache_proto_goTypes = nil
	file_internal_pb_cache_proto_depIdxs = nil
}
