// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.24.4
// source: internal/pb/cache.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PopulateDiskCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *PopulateDiskCacheRequest) Reset() {
	*x = PopulateDiskCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopulateDiskCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulateDiskCacheRequest) ProtoMessage() {}

func (x *PopulateDiskCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulateDiskCacheRequest.ProtoReflect.Descriptor instead.
func (*PopulateDiskCacheRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{0}
}

func (x *PopulateDiskCacheRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type PopulateDiskCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *PopulateDiskCacheResponse) Reset() {
	*x = PopulateDiskCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PopulateDiskCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopulateDiskCacheResponse) ProtoMessage() {}

func (x *PopulateDiskCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopulateDiskCacheResponse.ProtoReflect.Descriptor instead.
func (*PopulateDiskCacheResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{1}
}

func (x *PopulateDiskCacheResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BindMountCacheDirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Src string `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst string `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
}

func (x *BindMountCacheDirRequest) Reset() {
	*x = BindMountCacheDirRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindMountCacheDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMountCacheDirRequest) ProtoMessage() {}

func (x *BindMountCacheDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMountCacheDirRequest.ProtoReflect.Descriptor instead.
func (*BindMountCacheDirRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{2}
}

func (x *BindMountCacheDirRequest) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *BindMountCacheDirRequest) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

type BindMountCacheDirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BindMountCacheDirResponse) Reset() {
	*x = BindMountCacheDirResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pb_cache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindMountCacheDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindMountCacheDirResponse) ProtoMessage() {}

func (x *BindMountCacheDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_cache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindMountCacheDirResponse.ProtoReflect.Descriptor instead.
func (*BindMountCacheDirResponse) Descriptor() ([]byte, []int) {
	return file_internal_pb_cache_proto_rawDescGZIP(), []int{3}
}

var File_internal_pb_cache_proto protoreflect.FileDescriptor

var file_internal_pb_cache_proto_rawDesc = []byte{
	0x0a, 0x17, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x2e, 0x0a,
	0x18, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x35, 0x0a,
	0x19, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3e, 0x0a, 0x18, 0x42, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x72, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73,
	0x72, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x64, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x42, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xac, 0x01, 0x0a, 0x06, 0x43, 0x61, 0x63, 0x68, 0x65, 0x64, 0x12, 0x50, 0x0a, 0x11,
	0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73, 0x6b, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x73, 0x6b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x69, 0x73,
	0x6b, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50,
	0x0a, 0x11, 0x42, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x44, 0x69, 0x72, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x75,
	0x6e, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x4d, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x44, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67,
	0x61, 0x64, 0x67, 0x65, 0x74, 0x2d, 0x69, 0x6e, 0x63, 0x2f, 0x64, 0x61, 0x74, 0x65, 0x69, 0x6c,
	0x61, 0x67, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_pb_cache_proto_rawDescOnce sync.Once
	file_internal_pb_cache_proto_rawDescData = file_internal_pb_cache_proto_rawDesc
)

func file_internal_pb_cache_proto_rawDescGZIP() []byte {
	file_internal_pb_cache_proto_rawDescOnce.Do(func() {
		file_internal_pb_cache_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pb_cache_proto_rawDescData)
	})
	return file_internal_pb_cache_proto_rawDescData
}

var file_internal_pb_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_pb_cache_proto_goTypes = []interface{}{
	(*PopulateDiskCacheRequest)(nil),  // 0: pb.PopulateDiskCacheRequest
	(*PopulateDiskCacheResponse)(nil), // 1: pb.PopulateDiskCacheResponse
	(*BindMountCacheDirRequest)(nil),  // 2: pb.BindMountCacheDirRequest
	(*BindMountCacheDirResponse)(nil), // 3: pb.BindMountCacheDirResponse
}
var file_internal_pb_cache_proto_depIdxs = []int32{
	0, // 0: pb.Cached.PopulateDiskCache:input_type -> pb.PopulateDiskCacheRequest
	2, // 1: pb.Cached.BindMountCacheDir:input_type -> pb.BindMountCacheDirRequest
	1, // 2: pb.Cached.PopulateDiskCache:output_type -> pb.PopulateDiskCacheResponse
	3, // 3: pb.Cached.BindMountCacheDir:output_type -> pb.BindMountCacheDirResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_pb_cache_proto_init() }
func file_internal_pb_cache_proto_init() {
	if File_internal_pb_cache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pb_cache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopulateDiskCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PopulateDiskCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindMountCacheDirRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pb_cache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindMountCacheDirResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pb_cache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_cache_proto_goTypes,
		DependencyIndexes: file_internal_pb_cache_proto_depIdxs,
		MessageInfos:      file_internal_pb_cache_proto_msgTypes,
	}.Build()
	File_internal_pb_cache_proto = out.File
	file_internal_pb_cache_proto_rawDesc = nil
	file_internal_pb_cache_proto_goTypes = nil
	file_internal_pb_cache_proto_depIdxs = nil
}
