name: Release JS

on:
  push:
    branches:
      - main
    paths:
      - js/package.json

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-env

      - name: Build JS package
        run: make build-js

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./js/package.json
          access: public
