name: Test

on:
  push:
  workflow_call:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-env

      - name: Start background services
        run: dev &

      - name: Build Go binaries
        run: make build

      - name: Run Go tests
        run: make test

  test-fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-env

      - name: Start background services
        run: dev &

      - name: Build Go binaries
        run: make build

      - name: Setup DateiLager project
        run: make setup-local

      - name: Start DateiLager server
        run: make server &

      - name: Run fuzz tests
        run: make test-fuzz

  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-env

      - name: Start background services
        run: dev &

      - name: Build Go binaries
        run: make build

      - name: Setup DateiLager project
        run: make setup-local

      - name: Start DateiLager server
        run: make server &

      - name: Run JS tests
        run: make test-js

      - name: Run JS lints
        run: make lint-js

  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
