name: Test

on:
  push:
  workflow_call:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    runs-on: ubuntu-latest-l
    strategy:
      matrix:
        filesystem: [ext4, xfs]
    steps:
      - name: Setup XFS filesystem
        if: matrix.filesystem == 'xfs'
        run: |
          cd /
          sudo mkdir -p /mnt/xfs
          sudo truncate -s 20G /mnt/xfs.img
          sudo mkfs.xfs -m reflink=1 /mnt/xfs.img
          sudo mount -o loop /mnt/xfs.img $GITHUB_WORKSPACE
          sudo chown $USER:$USER $GITHUB_WORKSPACE
          findmnt

      - name: Setup LVM devices
        run: |
          sudo truncate -s 5G /var/tmp/lvm-base.img
          sudo truncate -s 5G /var/tmp/lvm-base-cache.img
          sudo truncate -s 5G /var/tmp/lvm-thin1.img
          sudo truncate -s 5G /var/tmp/lvm-thin2.img

          base_device=$(sudo losetup --find --show /var/tmp/lvm-base.img)
          read_through_base_device=$(sudo losetup --find --show /var/tmp/lvm-read-through-base.img)
          thin1_device=$(sudo losetup --find --show /var/tmp/lvm-thin1.img)
          thin2_device=$(sudo losetup --find --show /var/tmp/lvm-thin2.img)

          echo "DL_BASE_PV=$base_device" >> $GITHUB_ENV
          echo "DL_BASE_LV_FORMAT=${{ matrix.filesystem }}" >> $GITHUB_ENV
          echo "DL_READ_THROUGH_BASE_PV=$read_through_base_device" >> $GITHUB_ENV
          echo "DL_THINPOOL_PV_GLOBS=$thin1_device,$thin2_device" >> $GITHUB_ENV
          echo "DL_THINPOOL_CACHE_LV_SIZE_KIB=2097152" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-env

      - name: Start background services
        run: dev &

      - name: Build Go binaries
        run: make build

      - name: Use XFS for tmpdirs
        if: matrix.filesystem == 'xfs'
        run: |
          mkdir -p $GITHUB_WORKSPACE/tmp
          export TMPDIR=$GITHUB_WORKSPACE/tmp
          echo "TMPDIR=$GITHUB_WORKSPACE/tmp" >> $GITHUB_ENV
          echo "DL_USE_REFLINKS=1" >> $GITHUB_ENV

      - name: Run Go tests
        run: make test-integration

      - name: Run Go benchmarks
        run: make bench
        env:
          DL_OVERLAY_BENCH: true
          DL_LVM_BENCH: true

  test-fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-env

      - name: Start background services
        run: dev &

      - name: Build Go binaries
        run: make build

      - name: Setup DateiLager project
        run: make setup-local

      - name: Start DateiLager server
        run: make server & > server.out

      - name: Wait for DateiLager server
        run: timeout 20 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 5051

      - name: Run fuzz tests
        run: make test-fuzz

      - name: Get server output
        if: always()
        run: cat server.out

  test-js:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup development environment
        uses: ./.github/actions/setup-env

      - name: Start background services
        run: dev &

      - name: Build Go binaries
        run: make build

      - name: Setup DateiLager project
        run: make setup-local

      - name: Start DateiLager server
        run: make server &

      - name: Wait for DateiLager server
        run: timeout 20 sh -c 'until nc -z $0 $1; do sleep 1; done' localhost 5051

      - name: Run JS tests
        run: make test-js

      - name: Run JS lints
        run: make lint-js

  golangci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.4"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=2m
