name: Test

on:
  push:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/setup-env
    - run: nix develop -c dev &
    - run: nix develop -c make build
    - run: nix develop -c make test
